teams = [
     "Portugal",
    "South Korea",
    "Uruguay",
    "Ghana",
    "Netherlands",
    "Senegal",
    "Equator",
    "Qatar",
    "England",
    "USA",
    "Iran",
    "Wales",
    "Argentina",
    "Poland",
    "Mexico",
    "Saudi Arabia",
    "France",
    "Australia",
    "Tunisia",
    "Danmark",
    "Japan",
    "Spain",
    "Germany",
    "Costa Rica",
    "Morocco",
    "Crotia",
    "Belgium",
    "Canada",
    "Brazilia",
    "Swizeland",
    "Cameroun",
    "Serbia",
   
]